"""
codesheet.xlsx_sheet — the code analysis sheet as an Excel workbook.

to_xlsx(sd, path)   writes three worksheets from a SheetData (codesheet.sheet.run_all):
    "Code summary"    the title block, then every section as its own table — reads like the printed sheet
    "Determinations"  one flat, filterable row per determination (section, block, item, value, unit,
                      basis, clause, edition, page, flags) for sorting, pivoting or pasting elsewhere
    "Flags & notes"   reviewer flags, model notes, and what this draft does not cover

Values stay numeric where the rule produced a number, so the workbook can be used in formulas.
Like the HTML sheet this is a DRAFT for a registered professional's review, and says so.
"""
from __future__ import annotations

import datetime, pathlib
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from codesheet.determinations import Bylaw, Determination
from codesheet.sheet import SheetData, Section

# fonts and fills reused across the workbook
_TITLE = Font(bold=True, size=14)
_BOLD = Font(bold=True)
_KEY = Font(color="7A8291", size=9)
_NOTE = Font(italic=True, color="7A8291", size=9)
_SEC = Font(bold=True, color="FFFFFF")
_SEC_FILL = PatternFill("solid", fgColor="1E2126")
_HEAD = Font(bold=True, size=9, color="4B5563")
_HEAD_FILL = PatternFill("solid", fgColor="F3F4F6")
_DRAFT = Font(bold=True, color="C8352B")
_FLAG = Font(color="C8352B")
_WRAP = Alignment(wrap_text=True, vertical="top")
_TOP = Alignment(vertical="top")

DRAFT_TEXT = ("DRAFT — FOR REVIEW. Generated by rules; every line cites its clause. Not a compliance determination. "
              "To be reviewed and sealed by the Coordinating Registered Professional.")

SUMMARY_COLS = [("Block", 10), ("Item", 40), ("Value", 16), ("Unit", 9), ("Basis", 72), ("Clause", 26), ("Page", 8), ("Flags", 44)]
FLAT_COLS = [("Section", 9), ("Section title", 40), ("Block", 10), ("Item", 40), ("Key", 34), ("Value", 16), ("Unit", 9),
             ("Basis", 72), ("Clause", 26), ("Edition", 26), ("Page", 8), ("Flags", 44)]


def _value(d: Determination) -> Any:
    """A cell value: numbers stay numbers; lists are joined; None shows as a dash."""
    v = d.value
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, (int, float)):
        return v
    if isinstance(v, list):
        return ", ".join(str(x) for x in v) or "—"
    return str(v)


def _clauses(d: Determination) -> tuple[str, str, str]:
    """(clause ids, editions, pages), one line per clause, in the same order."""
    ids = [c.id + (f".({c.sentence})" if c.sentence else "") for c in d.clauses]
    eds = [c.edition for c in d.clauses]
    pages = [str(c.page) if c.page else "" for c in d.clauses]
    return "\n".join(ids), "\n".join(eds), "\n".join(pages)


def _set_widths(ws, cols):
    for i, (_, w) in enumerate(cols, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def _header_row(ws, row: int, cols):
    for i, (name, _) in enumerate(cols, start=1):
        c = ws.cell(row=row, column=i, value=name)
        c.font, c.fill = _HEAD, _HEAD_FILL


def _det_cells(d: Determination) -> list[Any]:
    ids, _eds, pages = _clauses(d)
    return [d.block or "", d.label, _value(d), d.unit, d.because, ids, pages, "\n".join(d.flags)]


def _write_section(ws, row: int, s: Section) -> int:
    """Section banner, optional note, header, rows. Returns the next free row."""
    c = ws.cell(row=row, column=1, value=f"{s.number}")
    c.font, c.fill = _SEC, _SEC_FILL
    t = ws.cell(row=row, column=2, value=s.title)
    t.font, t.fill = _SEC, _SEC_FILL
    for col in range(3, len(SUMMARY_COLS) + 1):
        ws.cell(row=row, column=col).fill = _SEC_FILL
    row += 1
    if s.note:
        ws.cell(row=row, column=2, value=s.note).font = _NOTE
        row += 1
    _header_row(ws, row, SUMMARY_COLS)
    row += 1
    if not s.dets:
        ws.cell(row=row, column=2, value="— none —").font = _NOTE
        return row + 2
    for d in s.dets:
        for i, v in enumerate(_det_cells(d), start=1):
            cell = ws.cell(row=row, column=i, value=v)
            cell.alignment = _WRAP if i in (2, 5, 6, 7, 8) else _TOP
            if i == 8 and v:
                cell.font = _FLAG
        row += 1
    return row + 1


def _summary_sheet(ws, sd: SheetData, edition: str, sheet_no: str, revision: str):
    b = sd.building
    law = Bylaw(edition)
    ws.title = "Code summary"
    _set_widths(ws, SUMMARY_COLS)
    ws.cell(row=1, column=1, value=f"{b.project_name} — Building Code Analysis").font = _TITLE
    ws.cell(row=2, column=1, value=" · ".join(x for x in (b.site.address, b.site.legal_description or "") if x)).font = _KEY
    meta = [("Applicable code", law.edition), ("Project no.", b.project_number or "—"),
            ("Permit application", b.permit_application_date or "—"), ("Blocks (firewall-separated)", " · ".join(b.blocks())),
            ("Sprinklered", "yes — throughout" if b.is_sprinklered else "no"), ("Streets faced", b.site.streets_faced),
            ("Generated", datetime.date.today().isoformat()), ("Sheet", f"{sheet_no} · {revision}")]
    row = 4
    for k, v in meta:
        ws.cell(row=row, column=1, value=k).font = _KEY
        ws.cell(row=row, column=2, value=v)
        row += 1
    ws.cell(row=row, column=1, value=DRAFT_TEXT).font = _DRAFT
    row += 2
    for s in sd.sections:
        row = _write_section(ws, row, s)
    ws.freeze_panes = None


def _flat_sheet(ws, sd: SheetData):
    ws.title = "Determinations"
    _set_widths(ws, FLAT_COLS)
    _header_row(ws, 1, FLAT_COLS)
    row = 2
    for s in sd.sections:
        for d in s.dets:
            ids, eds, pages = _clauses(d)
            vals = [s.number, s.title, d.block or "", d.label, d.key, _value(d), d.unit, d.because, ids, eds, pages, "\n".join(d.flags)]
            for i, v in enumerate(vals, start=1):
                cell = ws.cell(row=row, column=i, value=v)
                cell.alignment = _WRAP if i in (4, 8, 9, 10, 11, 12) else _TOP
                if i == 12 and v:
                    cell.font = _FLAG
            row += 1
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(FLAT_COLS))}{max(row - 1, 1)}"


def _notes_sheet(ws, sd: SheetData):
    ws.title = "Flags & notes"
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 110
    row = 1
    ws.cell(row=row, column=1, value=f"Reviewer flags ({len(sd.flags)})").font = Font(bold=True, color="C8352B")
    row += 1
    _header_row(ws, row, [("Where", 0), ("Flag", 0)])
    row += 1
    if not sd.flags:
        ws.cell(row=row, column=2, value="none").font = _NOTE
        row += 1
    for where, text in sd.flags:
        ws.cell(row=row, column=1, value=where).alignment = _WRAP
        ws.cell(row=row, column=2, value=text).alignment = _WRAP
        row += 1
    row += 1
    for title, items in (("Model notes", sd.building.notes), ("Not covered by this draft", sd.not_covered)):
        ws.cell(row=row, column=1, value=title).font = _BOLD
        row += 1
        for t in items:
            ws.cell(row=row, column=2, value=t).alignment = _WRAP
            row += 1
        row += 1


def to_xlsx(sd: SheetData, path: pathlib.Path, edition: str = "vbbl-2025", sheet_no: str = "A0.01", revision: str = "Draft") -> pathlib.Path:
    """Write the workbook and return its path."""
    wb = Workbook()
    _summary_sheet(wb.active, sd, edition, sheet_no, revision)
    _flat_sheet(wb.create_sheet(), sd)
    _notes_sheet(wb.create_sheet(), sd)
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path
